spring:
  application:
    name: stream-processor

# Kafka Configuration
kafka:
  bootstrap-servers: kafka:9092
  topics:
    page-views: page_views
    ad-clicks: ad_clicks
  consumer:
    group-id: stream-processor-group
    concurrency: 3  # Number of concurrent consumer threads (one per partition)

# Output Configuration
output:
  database:
    path: ./output/attributed_page_views.db

# Watermark Configuration
watermark:
  allowed-lateness-minutes: 15

# Redis Configuration
data:
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}

# non-blocking Redis client
  lettuce:
    pool:
      # Maximum number of active connections in the pool
      max-active: 50
      # Maximum time a connection allocation should block before throwing an exception
      max-wait: 2000ms
      # Maximum number of idle connections in the pool
      max-idle: 10
      # Minimum number of idle connections to keep open
      min-idle: 2

# Logging Configuration
logging:
  level:
    root: INFO
    com.kokhrimenko.tesla.model_s: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/stream-processor.log
